"""followers

Revision ID: 168ca3e54759
Revises: 73fe8f9b4f31
Create Date: 2026-05-22 12:03:00.341995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168ca3e54759'
down_revision = '73fe8f9b4f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
